<!DOCTYPE html>
<html lang="pt_br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Aleck Yann Mattos">
   	<meta name="description" content="<?= $description ?>">
    <meta property="og:locale" content="pt_BR" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="GetDoctors - Um médico pra chamar de seu!" />
	<link rel=”canonical” href="<?= base_url() ?>" />
    <title><?= $title ?></title>

	<link href='https://fonts.googleapis.com/css?family=Ubuntu:400,500,700,300' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Signika+Negative:400,300,600,700' rel='stylesheet' type='text/css'>

	<!-- START FAVICONS -->
	<link rel="icon" href="<?= base_url() ?>public/images/ico/favicon.ico">
    <link rel="apple-touch-icon" sizes="144x144" href="<?= base_url() ?>public/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon" sizes="114x114" href="<?= base_url() ?>public/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon" sizes="72x72" href="<?= base_url() ?>public/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon" sizes="57x57" href="<?= base_url() ?>public/images/ico/apple-touch-icon-57-precomposed.png">

  </head>
  <body>

<h3>Termos de Uso do Serviço</h3>
		<p>getdoctors é uma aplicação interativa móvel (app) fornecidos por getdoctors.Ltda ( “getdoctors”). O uso do aplicativo encontra-se disponível em nosso website em https://getdoctors.com.br (coletivamente, os “Serviços”) é regido pelos termos e condições deste Contrato. Embora acessíveis por outros, os serviços (que incluem conteúdo) são destinados ao acesso e uso apenas por clientes no Brasil. Por favor, leia estes termos e condições de uso (o “Termos de Uso”) cuidadosamente antes de acessar ou usar os Serviços. No presente contrato, getdoctors é referido como “nós”.</p>
		<h3>Termos Gerais de Condição</h3>
		<p>POR FAVOR: LEIA ESTE “TERMO” CUIDADOSAMENTE ANTES DE EFETUAR O CADASTRO NO “<i>GETDOCTORS</i>”. QUALQUER PESSOA, LEGALMENTE CAPAZ, DORAVANTE DENOMINADA “PACIENTE”, QUE UTILIZE OS SERVIÇOS DO “<i>GETDOCTORS</i>”, DEVE ACEITAR ESTE “TERMO” E TODAS AS POLÍTICAS E PRINCÍPIOS QUE O REGEM.

		Ao acessar ou utilizar os Serviços da getdoctors, você concordará na vinculação deste Acordo, publicado e acessível através de nosso aplicativo ou site no momento de seu acesso ou uso, e para usar os Serviços de acordo com os termos e condições deste Contrato, a nossa política de privacidade getdoctors/privacidade e quaisquer termos e condições adicionais que são aqui referenciados ou que de outra forma possam ser aplicáveis para as características específicas dos serviços ou para os produtos que disponibilizamos a você através da getdoctors (todos os quais são considerados parte deste Acordo).

		Se você não concordar com os termos e condições de uso dos Serviços conforme estabelecido no presente termo, não poderá utilizar os Serviços.

		A Internet é um meio de evolução. Se precisar alterar os termos deste Contrato, no futuro, publicaremos os termos revisados e Condições de Uso através de nosso aplicativo ou site e atualizaremos a “última revisão” para acompanhar as mudanças da sociedade e do mercado. Você concorda em rever estes Termos e Condições de Uso cada vez que utilizar os Serviços de modo que você está ciente de quaisquer modificações feitas a este Acordo. Ao continuar a utilizar os Serviços depois que postar tais mudanças, você concorda com os termos deste Contrato, conforme modificado.

		Este TERMO está disponível ao final da página principal do SITE e no link Termos de Uso como também Política de Privacidade, para verificação de qualquer consumidor, independentemente de cadastro prévio no APLICATIVO.</p>
		<h3><i>GETDOCTORS</i></h3>
		<p>A <i>GETDOCTORS</i> foi projetada para oferecer informações e um meio para que você possa obter consulta domiciliar e tratamento de condições médicas comuns, facilitando a conexão entre você e os profissionais de saúde nas proximidades através da utilização do Aplicativo. Para evitar dúvidas, a palavra em maiúsculas “Serviços”, usado no presente Acordo refere-se apenas para a nossa aplicação, website e conteúdo relacionado e não se refere ao atendimento presencial de consulta e tratamento que os usuários recebem de profissionais de saúde.</p>
		<h3>COMO USAR O APLICATIVO</h3>
		<p>Para usar o aplicativo, você primeiro precisa cadastrar na getdoctors. Ao inscrever-se, você é obrigado a nos fornecer algumas informações, como seu nome completo, endereço, data de nascimento, informações de cartão de crédito. No futuro, nós também poderemos exigir que os usuários forneçam informações sobre o seguro (Plano de Saúde) e sintomas que estejam sentindo antes da consulta. Após a conclusão bem-sucedida do processo de inscrição, iremos fornecer-lhe com uma conta pessoal, acessível para você com uma senha de sua escolha.
		Você tem que ter 18 anos de idade ou mais e residir em uma jurisdição em que oferecemos o aplicativo para usar o serviço. Se você reside em uma jurisdição que restringe o uso do aplicativo, você deve respeitar esses limites e você não deve usar o aplicativo. Ao usar o Aplicativo você está declarando que é da idade legal para celebrar um contrato vinculativo.

		O aplicativo é projetado para permitir que você envie um pedido de serviços de consulta médica não emergenciais para um profissional de saúde. O receptor GPS – que deve ser instalado no dispositivo móvel no qual você fez o download do aplicativo – detecta a sua localização. O aplicativo identifica para o paciente, profissionais de saúde que tenham a devida licença médica e inscrição em seu conselho de classe, e que nos contratou para realizar serviços relacionados.

		Você será capaz de selecionar um profissional de saúde que você deseja o qual irá executar serviços de saúde para você. Antes da seleção o paciente poderá encaminhar seus sintomas e informações que achar relevante para o médico que irá selecionar. (Essas informações não serão reveladas a terceiros ficando exclusivamente com o cliente/paciente a escolha para quem revelar, porém a getdoctors poderá usar tais informações respeitando o sigilo dos dados pessoais do cliente, para banco de dados e estudo de impacto regional de patologias e sintomas.)

		Após a seleção, o aplicativo, em seguida, envia uma mensagem para o profissional que você selecionou e pede para o profissional se ele ou ela gostaria de lhe fornecer os serviços de saúde solicitados. No caso de um profissional de saúde concordar em lhe fornecer os serviços de saúde, os horários do agendamento e os serviços prestados pelo profissional de saúde será em nome do mesmo. “Nós” não fazemos nenhuma representação ou garantia a você que qualquer profissional de saúde estará disponível para realizar os serviços de saúde.

		A <i>GETDOCTORS</i> NÃO ESTÁ ENVOLVIDA NA PRÁTICA DA MEDICINA, NÃO PRESTA SERVIÇOS MÉDICOS, E NÃO É UM PROFISSIONAL DE SAÚDE. OS PROFISSIONAIS DE SÁUDE COM OS QUAIS ESTABELECER UMA RELAÇÃO DE TRATAMENTO É O ÚNICO RESPONSÁVEL PELO FORNECIMENTO DE SERVIÇOS MÉDICOS. “NÓS” SÓ AGIMOS COMO UMA PLATAFORMA DE TECNOLOGIA PARA CONECTÁ-LO COM PROFISSIONAIS DE SAÚDE QUE POSSAM ESTAR INTERESSADOS EM FORNECER-LHE SERVIÇOS MÉDICOS.</p>
		<h3>DECLARAÇÃO DE USO</h3>
		<p>Você declara e garante que as informações que você fornecer para nós são precisas e completas. Você reconhece e concorda que temos o direito em todos os momentos para verificar as informações fornecidas e negar o seu uso dos Serviços, a qualquer momento, por qualquer motivo ou sem motivo.

		Você só pode acessar os serviços usando meios autorizados. É sua responsabilidade verificar para garantir que você baixe o aplicativo correto para o seu dispositivo. Nós não somos responsáveis se você não tiver um dispositivo compatível ou se você baixar a versão errada da aplicação para o seu dispositivo.</p>
		Ao acessar ou utilizar os Serviços, você concorda ainda que:

		<li>Você só vai usar os Serviços para o seu uso pessoal e exclusivo e você não vai revendê-los a um terceiro;</li>
		<li>Você não pode copiar ou distribuir o conteúdo dos Serviços ou outros serviços</li>
		<li>Você não vai enviar ou transmitir qualquer comunicação ou conteúdo de qualquer tipo que infringir ou violar quaisquer direitos de qualquer das partes;</li>
		<li>Você não usará os Serviços para qualquer efeito em violação do local, estadual, federal ou leis internacionais;</li>
		<li>Você não vai usar os Serviços como um meio para distribuir publicidade ou outro material não solicitado a terceiros;</li>
		<li>Você não vai se passar por outra pessoa;</li>
		<li>Você não irá publicar material que seja ilegal, obsceno, difamatório, ameaçador, ofensivo, abusivo, insultuosa, de ódio ou embaraçoso para qualquer outra pessoa ou entidade, conforme determinado por nós a nosso exclusivo critério;</li>
		<li>Você vai cumprir todos os termos de terceiros aplicáveis de acordo ao usar os Serviços (por exemplo, o seu contrato de serviços de dados sem fio);</li>
		<li>Você vai garantir que nenhuma pessoa não autorizada tenha acesso ao seu dispositivo móvel ou suas senhas <i>GETDOCTORS</i> ou contas;</li>
		<li>Você vai avisar-nos imediatamente em caso suas senhas <i>GETDOCTORS</i> ou contas forem comprometidas;</li>
		<li>Você não vai ceder ou transferir sua conta para qualquer outra pessoa ou entidade;</li>
		<li>Você não vai tentar prejudicar os Serviços ou prejudicar o bom funcionamento da rede de forma alguma;</li>
		<li>Você vai fornecer-nos com qualquer prova de identidade que possa ser solicitado.</li>

		Reservamo-nos o direito de rescindir imediatamente o seu uso dos Serviços, caso você deixe de cumprir qualquer das regras anteriores.

		Você é livre para estabelecer um link de hipertexto para nossos serviços, desde que o link não declare ou implique qualquer patrocínio do seu site ou serviço por nós ou por nossos Serviços. No entanto, você não pode, sem a nossa autorização prévia por escrito, criar algum quadro ou link embutido em qualquer parte do conteúdo dos nossos serviços, ou incorporar em outro site ou outro serviço qualquer um dos nossos materiais, conteúdo ou propriedade intelectual. ESTE “TERMO” É APLICÁVEL E DE USO EXCLUSIVO DOS “PACIENTES”.

		<h3>NOSSO DIREITO DE USAR AS INFORMAÇÕES FORNECIDAS</h3>
		<p>Nós podemos, a nosso critério, permitir que você poste ou envie conteúdo e outros materiais através dos Serviços (coletivamente, “conteúdo fornecido pelo usuário”). Você nos concede, e a qualquer pessoa autorizada por nós, um irrevogável, não-exclusiva, irrestrita licença mundial, perpétua, isenta de royalties, para usar, copiar, modificar, transmitir, vender, explorar, criar obras derivadas, distribuir, e / ou executar publicamente ou exibir tal conteúdo fornecido pelo usuário, no todo ou em parte, em qualquer forma ou meio (conhecida agora ou no futuro desenvolvida), para qualquer propósito que escolhemos. Além disso, você nos concede, e qualquer pessoa autorizada por nós, o direito de identificá-lo como o autor de qualquer conteúdo fornecido pelo usuário enviado por você. Você não receberá qualquer compensação de qualquer espécie para o uso de qualquer conteúdo fornecido pelo usuário enviado por você.

		Você reconhece que a <i>GETDOCTORS</i> só age como um canal passivo para a distribuição do conteúdo fornecido pelo usuário e não é responsável ou responsável perante si ou a terceiros pelo conteúdo ou precisão do conteúdo fornecido pelo usuário. Você entende que nós não temos nenhuma obrigação de monitorar todas as áreas dos Serviços através do qual os usuários podem postar conteúdo fornecido pelo usuário. No entanto, nos reservamos o direito em todos os momentos, a nosso exclusivo critério, para a tela conteúdo fornecido pelo usuário e para editar, mover, excluir e / ou recusar-se a aceitar qualquer conteúdo fornecido pelo usuário que, em nosso julgamento, viole o presente Acordo ou de outra forma inaceitável ou inadequada, seja por razões legais ou outros.

		Qualquer uso que você faz do conteúdo fornecido pelo usuário é inteiramente por sua conta e risco. Você declara e garante que qualquer conteúdo fornecido pelo usuário publicado ou transmitido por você é originalmente por você e não copiado do trabalho de terceiros ou de outra forma infrinja quaisquer terceiros, direitos de propriedade intelectual, direitos de privacidade ou direitos de publicidade e não contém quaisquer declarações difamatórias ou depreciativos. Além disso, você declara e garante que tem o direito de conceder a licença acima descrito.

		Você concorda em indenizar e isentar a <i>GETDOCTORS</i>, afiliados a <i>GETDOCTORS</i>, e cada um dos seus e seus respectivos conselheiros, diretores, gerentes, funcionários, acionistas, agentes, representantes, licenciados, sucessores e cessionários de e contra todas e quaisquer perdas, despesas, danos e custos, incluindo honorários advocatícios, que surgem de qualquer conteúdo fornecido pelo usuário publicado ou transmitido através dos Serviços por você ou por outras pessoas usando a sua conta.</p>
		<h3>DO PAGAMENTO</h3>
		<p>Não há custo para se registrar conosco ou baixar o aplicativo em seu dispositivo móvel. Você só é cobrado quando você realmente usar os Serviços de agendamento no caso uma consulta com um profissional de saúde. Cada profissional de saúde define suas próprias taxas ou para o seu tempo e serviços, mas o seu pagamento a eles inclui uma parte que é mantida por nós para os nossos serviços administrativos em conexão com o aplicativo. Reservamo-nos o direito de introduzir uma taxa no futuro para baixar o aplicativo como registrar com a gente. Se decidirmos introduzir tal taxa, iremos informá-lo em conformidade e permitir que você quer continuar ou encerrar sua conta.

		As taxas que se aplicam para os serviços de consulta médica prestados pelos profissionais de saúde podem ser encontradas em nosso site e através do aplicativo. Estes podem ser modificados ou atualizados de tempos em tempos. É sua responsabilidade manter-se informado sobre as taxas atuais para os serviços médicos disponibilizados através do aplicativo.

		A <i>GETDOCTORS</i> transmite, em nome do profissional de saúde, para cobrar-lhe os serviços médicos prestados a você por esse profissional de saúde. Você concorda que você vai pagar por todos os serviços médicos que receber do profissional de saúde, e que a <i>GETDOCTORS</i> pode cobrar sua conta de cartão de crédito, como fornecido por você quando se inscrever para os serviços, para os serviços médicos, incluindo todos os impostos e taxas atrasadas, como aplicável, que podem ser acumulados por ou em conexão com a sua conta. Você é responsável pelo pagamento antecipado de todas as taxas e por fornecer a <i>GETDOCTORS</i> com uma conta de cartão de crédito válido para o pagamento de todas as taxas em todos os momentos. Qualquer pagamento feito não é reembolsável.

		Nós usamos um processador de pagamento de terceiros (o “Processador de Pagamento”) para nos conectar-se a sua conta de cartão de crédito. O processamento de pagamentos ou créditos, conforme aplicável, em conexão com o uso do aplicativo será sujeito aos termos, condições e políticas de privacidade do processador de pagamento e o emissor do seu cartão de crédito para além deste Acordo. Nós não somos responsáveis por quaisquer erros por parte do processador de pagamento ou o emissor do seu cartão de crédito. Em conexão com o uso dos Serviços (e, especificamente, em conexão com o agendamento de uma telefônica ou pessoalmente consulta com um profissional de saúde), a <i>GETDOCTORS</i> irá obter certos detalhes da transação, que usaremos exclusivamente de acordo com nossa Política de Privacidade.

		No momento nós não processaremos quaisquer pedidos de plano de saúde, nem os profissionais de saúde processam reivindicações em seu nome. Embora as consultas / tratamentos que você receba de profissionais de saúde através da aplicação pode ou não ser coberto pelo seu seguro, você é o único que deverá entrar em contato com o seu plano de saúde, determinar se a cobertura se aplica e apresentar um pedido. Você é responsável para a taxa cheia (e por pagar a taxa com antecedência), independentemente de você mais tarde ser capaz de receber o reembolso do seu plano de saúde para parte ou todo o custo.

		A <i>GETDOCTORS</i> poderá cobrar por consultas canceladas quando o médico estiver na porta do usuário, todo cancelamento deve ser realizado antecipadamente, a conduta de cobrar não significa cobrança indevida, pois o usuário terá o direito do atendimento médico mesmo que não seja realizado no dia do cancelamento, podendo ser agendado para outro dia que o usuário desejar, a cobrança ocorrerá como política para desestimular a solicitação do profissional médico de forma irregular, portanto somente solicite um profissional de saúde caso realmente necessite.</p>
		<h3>DIREITOS AUTORAIS</h3>
		<p>A <i>GETDOCTORS</i> sozinha (e seus licenciadores, se for o caso) terá todos os direitos, títulos e interesses, incluindo todos os direitos de propriedade intelectual, em e para os Serviços e quaisquer sugestões, ideias, solicitações de melhoria, comentários, recomendações ou outras informações fornecidas por você ou por qualquer outra parte relativa aos Serviços. Qualquer cópia, alteração, revisão, melhoria, adaptação, tradução ou trabalho derivado ou criado a partir dos Serviços serão propriedade única e exclusivamente da <i>GETDOCTORS</i>, e / ou, conforme o caso, os fornecedores da <i>GETDOCTORS</i> de terceiros, bem como em qualquer e todas os direitos de patentes, direitos autorais, direitos de segredo comercial, direitos de marca, e todos os outros direitos de propriedade, no mundo inteiro, e você decide atribuir a <i>GETDOCTORS</i> qualquer e todos os seus direitos, títulos ou interesses nos Serviços ou qualquer modificação ou trabalho derivado do Serviços. Você não deve remover ou autorizar ou permitir que terceiros possam remover qualquer legenda ou direitos de propriedade dos Serviços.

		Os materiais nos Serviços estão protegidas por copyright a nós e / ou outros detentores de direitos aplicáveis. Você pode baixar e imprimir uma única cópia dos materiais a partir dos Serviços apenas para seu próprio uso pessoal e não comercial, desde que você mantenha intactos todos os créditos e direitos de autor e outros avisos de propriedade. Qualquer outro uso dos materiais é estritamente proibida sem a nossa autorização prévia e por escrito a permissão do detentor dos direitos aplicáveis (s).</p>
		<h3>LICENÇA DE USO</h3>
		<p>Sujeito a sua conformidade com os termos e condições deste Contrato, A <i>GETDOCTORS</i> lhe concede uma licença não exclusiva, licença limitada, não transferível para baixar e instalar uma cópia do aplicativo em um dispositivo móvel que você possui ou o controle e para executar tal cópia do pedido exclusivamente para seu próprio uso pessoal.

		Você não deve (i) licenciar, sublicenciar, vender, vender, transferir, ceder, distribuir ou explorar comercialmente ou disponibilizar a terceiros a Aplicação de qualquer forma; (Ii) modificar ou realizar trabalhos derivados com base no aplicativo; (Iii) fazer engenharia reversa ou acessar o aplicativo, a fim de (a) desenho ou construir um produto ou serviço competitivo, (b) o projeto ou construir um produto usando idéias semelhantes, características, funções ou elementos gráficos do aplicativo ou (c) cópia quaisquer ideias, características, funções ou elementos gráficos do pedido; ou (v) lançar um programa ou script automatizado, incluindo, mas não limitado a, aranhas, lagartas web, web robôs, formigas web, indexadores web, bots, vírus ou worms ou qualquer programa que pode fazer várias solicitações do servidor por segundo ou encargos indevida ou dificulta a operação e / ou desempenho dos Serviços.</p>
		<h3>AVISO LEGAL</h3>
		<p>OS SERVIÇOS E QUAISQUER INFORMAÇÕES CONTIDAS ou fornecidos através do aplicativo é voluntária. Consideraremos todo o acesso ou o uso como voluntário e de CONTA E RISCO DO USUÁRIO.

		Os serviços são exclusivamente projetados para permitir que você obtenha a consulta domiciliar e tratamento de condições médicas comuns, facilitando a conexão entre você e os prestadores de cuidados de saúde nas proximidades. Nenhum dispositivo de SERVIÇOS é ou deve ser considerado ou utilizado como um substituto PARA, o aconselhamento médico, diagnóstico ou tratamento. Os serviços prestados no pedido são aqui para ajudar a conectar você e apenas prestadores de cuidados de saúde nas proximidades. Qualquer informação contida nos Serviços não deve ser invocado como base de qualquer decisão de cuidados de saúde. Os serviços não constituem a prática de qualquer médico, de enfermagem ou outro conselho profissional de saúde, diagnóstico ou tratamento.

		Não desrespeite, ou evite o atraso na obtenção de atendimento médico de seu profissional de saúde licenciado ou outro QUALIFICADO FORNECEDOR DE CUIDADOS MÉDICOS por causa de algo que LEU ATRAVÉS DO NOSSO aplicativo ou site. Se você tiver ou suspeitar que você tem um problema ou condição médica, você pode usar este aplicativo para tentar entrar em contato com QUALIFICADO profissional de saúde. No entanto, se você está enfrentando uma emergência médica, LIGUE PARA EMERGÊNCIA de ajuda médica do seu município.

		Nós não controlamos, o fornecimento, endossamos, asseguramos ou garantimos qualquer informação, produtos, serviços ou mercadorias fornecidas por qualquer dos prestadores de cuidados de saúde que você pode conectar-se com através dos Serviços.

		Nós também não asseguramos ou garantimos que os arquivos que podem estar disponíveis para download através dos Serviços estarão livres de infecções ou vírus, worms, cavalos de Tróia ou outro código que contém propriedades contaminantes ou destrutivas.

		Nós e nossos prestadores de serviços de tecnologia, não podem e não garantem contra erros, omissões, atrasos, interrupções ou perdas, incluindo perda de dados. Você pode baixar e usar os Serviços por sua própria conta e risco, e você é o único responsável por quaisquer danos ao seu dispositivo de hardware (s) ou perda de dados que resulte do download ou utilização dos Serviços. Usuários dos Serviços são responsáveis pela manutenção de um meio externo para os Serviços para a reconstrução de qualquer perda de dados.

		NÓS NÃO FAZEMOS QUALQUER GARANTIA EXPRESSA OU IMPLÍCITA, representações ou endossos DE QUALQUER ESPÉCIE (INCLUINDO, SEM LIMITAÇÃO, GARANTIAS DE TÍTULO OU NÃO VIOLAÇÃO, OU QUALQUER GARANTIA DE COMERCIALIZAÇÃO OU ADEQUAÇÃO A UM DETERMINADO FIM) EM RELAÇÃO AOS SERVIÇOS OU COM RESPEITO A QUALQUER INFORMAÇÃO, produto, serviço, mercadorias ou outros materiais fornecidos no ou através do Serviços (incluindo quaisquer consultas ou outros serviços que você possa obter de profissionais de saúde que você se conectar com através dos serviços).  NÓS NÃO GARANTIMOS nem a exatidão, integridade, oportunidade ou utilidade de qualquer informação, produtos, serviços, mercadorias ou outros materiais fornecidos através dos Serviços ou na Internet em geral. NÃO GARANTIMOS QUE OS SERVIÇOS SERÁ ININTERRUPTO, PONTUAL, SEGURO OU SEM ERROS. SEU ÚNICO E EXCLUSIVO REMÉDIO PARA INSATISFAÇÃO COM SERVIÇOS É PARAR DE USAR OS MESMOS.</p>
		<h3>LIMITAÇÃO DAS RESPONSABILIDADES</h3>
		<p>AO MÁXIMO PERMITIDO PELA LEI APLICÁVEL, EM NENHUM CASO A <i>GETDOCTORS</i> SERÁ RESPONSÁVEL POR VOCÊ OU QUALQUER TERCEIRO POR QUAISQUER DANOS DIRETOS, PUNITIVOS, INCIDENTAIS, INDIRETOS, EXEMPLARES, ESPECIAIS OU DERIVADOS (SEJA EM CONTRATO, (INCLUINDO NEGLIGÊNCIA), OU OUTRO) DECORRENTES DO PRESENTE ACORDO OU DO USO OU DA INCAPACIDADE DE USO DOS SERVIÇOS, INCLUINDO, SEM LIMITAÇÃO, quaisquer informações ou dados disponibilizados através dos serviços ou qualquer serviços executados por todos os fornecedores de cuidados de saúde que você se conectar com o aplicativo.

		Os serviços (incluindo reclamações de negligência médica contra os prestadores de saúde), MESMO QUE TENHAM SIDO AVISADOS ANTECIPADAMENTE DA POSSIBILIDADE DE TAIS DANOS. EM CASO A LIMITAÇÃO DA RESPONSABILIDADE é determinada por um tribunal de jurisdição competente SER APLICÁVEL, DO QUE A RESPONSABILIDADE MÁXIMA DA <i>GETDOCTORS</i> PARA TODAS AS REIVINDICAÇÕES (QUER EM CONTRATO, PREJUÍZO (INCLUINDO NEGLIGÊNCIA MÉDICA / ERRO MÉDICO), OU DE OUTRA FORMA) de qualquer tipo DECORRENTES DESTE CONTRATO NÃO EXCEDERÁ O VALOR DE UMA CONSULTA NO MUNICIPIO QUE SE ENCONTRA O USUARIO. A LIMITAÇÃO DA RESPONSABILIDADE DA <i>GETDOCTORS</i> abrangerá, SEM LIMITAÇÃO, QUALQUER MAU FUNCIONAMENTO TÉCNICO, ERRO DE COMPUTADOR OU PERDA DE DADOS, E qualquer outra lesão, DECORRENTES DO USO DOS SERVIÇOS TÉCNICOS.</p>
		<h3>INDENIZAÇÃO</h3>
		<p>Você concorda em indenizar e isentar a <i>GETDOCTORS</i>, e afiliadas a <i>GETDOCTORS</i>, e cada um dos seus e seus respectivos conselheiros, diretores, gerentes, funcionários, acionistas, agentes, representantes, licenciados, sucessores e cessionários de e contra todas e quaisquer perdas, despesas, danos e custos, incluindo honorários advocatícios, decorrentes do seu uso dos Serviços, violação deste Contrato por você ou qualquer outra pessoa utilizando a sua conta, ou sua violação de quaisquer direitos de terceiros. Reservamo-nos o direito de controlar a defesa de qualquer reclamação para o qual temos o direito de indenização ao respaldo desta seção. Nesse caso, você concorda em fornecer-nos com essa cooperação que for razoavelmente solicitado por nós.</p>
		<h3>ALTERAÇÃO E DESCONTINUIDADE DO CONTRATO</h3>
		<p>Reservamo-nos o direito de a qualquer momento e de tempos em tempos, modificar ou descontinuar, temporariamente ou permanentemente, os Serviços, ou qualquer parte dele, com ou sem aviso prévio. Você concorda que não será responsabilizada por você ou qualquer terceira parte por qualquer modificação, suspensão ou interrupção dos Serviços ou qualquer parte dele.</p>
		<h3>PRIVACIDADE</h3>
		<p>Seu uso dos Serviços está sujeito à Política de Privacidade da <i>GETDOCTORS</i>. Por favor, reveja esta política para que possa entender as informações que recolhemos através dos Serviços, como a usamos, e quando podemos compartilhar.</p>
		<h3>VIOLAÇÃO DE DIREITOS AUTORAIS</h3>
		<p>Se você é proprietário de direitos autorais que acredita que o seu material com direitos autorais foi reproduzido, publicado ou distribuído através dos serviços de uma forma que constitua violação de direitos autorais, por favor informe o nosso departamento jurídico designado pelo envio de aviso por escrito pelo correio do Brasil a Rua Gonçalves dias 729, cl 201, Batel, Curitiba – Paraná, CEP: 80.240-340:, ou por correio electrónico para david.stacciarini@gmail.com. Por favor, inclua as seguintes informações em sua notificação por escrito: (1) uma descrição detalhada do trabalho com direitos autorais que supostamente está sendo infringido; (2) uma descrição da localização do material supostamente infrator nos Serviços; (3) suas informações de contato, incluindo seu endereço, número de telefone e, se disponível, endereço de e-mail ou outro endereço eletrônico; (4) uma declaração sua indicando que você tem uma crença de boa-fé que o uso supostamente infrator não está autorizado pelo proprietário dos direitos autorais, seu advogado caso tenha; (5) uma declaração sua, feita sob pena de perjúrio, afirmando que a informação em seu aviso são precisas e que você está autorizado a agir em nome do proprietário dos direitos autorais; e (6) uma assinatura eletrônica ou física do proprietário dos direitos autorais ou alguém autorizado em nome do proprietário para afirmar violação de direitos autorais e de apresentar a declaração. Por favor, note que as informações de contato fornecidas neste parágrafo são para violação de direitos autorais. As suspeitas somente. As informações de contato para outros assuntos podem ser encontradas em outros lugares em nosso site ou através do aplicativo. getdoctors.com.br</p>
		<h3>DISPOSIÇÕES FINAIS</h3>
		<p>Este termo constitui a totalidade do acordo entre nós e você com relação ao assunto contido neste Contrato e substituem todos os anteriores e atuais acordos, propostas e comunicações, escrita ou oral, relacionado a esse assunto. Você também pode estar sujeito a termos e condições adicionais que podem ser aplicadas quando você usa os produtos ou serviços de terceiros que estão disponíveis através dos Serviços. Em caso de qualquer conflito entre tais termos de terceiros e condições e este Contrato, este irá governar. Este Contrato será regido e interpretado de acordo com as leis do Brasil, sem levar em conta qualquer conflito de provisões legais nelas contidas.

		Este Contrato é pessoal para você e você não pode atribuir a ninguém. Se qualquer disposição deste Acordo for considerada ilegal, nula ou por qualquer razão inaplicável, então essa disposição será considerada separável deste acordo e não afetará a validade e aplicabilidade de quaisquer disposições remanescentes. Este acordo não se destina a beneficiar qualquer terceiro, e não cria quaisquer terceiros beneficiários. Assim sendo, o presente acordo só pode ser invocado ou executado por você ou por nós.

		Você concorda que, independentemente de qualquer estatuto ou lei em contrário, qualquer reclamação ou causa de ação que você pode ter decorrentes ou relacionadas com a utilização dos Serviços ou este Contrato deve ser apresentado por você no prazo de três anos após tal reclamação ou causa de ação, ou ser barrado para sempre. Qualquer e todas as disposições deste Acordo, que seria razoavelmente esperado para ser realizada após o término ou expiração deste Acordo devem sobreviver e ser exequível após a rescisão ou término incluindo, sem limitação, as disposições relativas à propriedade, indenização, limitação de responsabilidade.</p>
		<hr>
		Revisão 01/03/<?= date('Y') ?>

		Direitos reservados a getdoctors.com.br

</body>
</html>
